// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbllifdsvjityyofiikp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdibGxpZmRzdmppdHl5b2ZpaWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjUxMzIsImV4cCI6MjA3MjUwMTEzMn0.HcnqwzamPXad56qdxuW1V86UTTCfXoyj7EjCSyS37YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});